name: hofninja_app
description: The most useful app for Wim Hof Breathing Method.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_session: ^0.1.7  # poprawne mieszanie/zarządzanie sesją audio
  wakelock_plus: ^1.2.5
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  vibration: ^3.1.4
  audioplayers: ^6.5.1
  rename: ^3.1.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/tutorial/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash.png"
  android: true
  ios: false
  web: false
  android_gravity: centerCrop

